version: '3.9'

services:
  app:
    container_name: app
    image: demo_swagger
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=10031992
      - MYSQL_HOST=mysql

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=10031992
      - MYSQL_DATABASE=demo_swagger